
development:
  adapter: postgresql
  encoding: unicode
  database: clubplayer_dev
  pool: 5
  username: vasilis
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: clubplayer_test
  pool: 5
  username: vasilis
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: clubplayer_prod
  pool: 5
  username: testing
  password: password1
